version: '3.1'

services:
        php:
                build:
                        context: php
                volumes:
                        - ./index:/usr/share/nginx/html
                depends_on:
                        - mysql

        nginx:
                build:
                        context: nginx
                ports:
                        - 1212:80
                depends_on:
                        - php
                volumes:
                        - ./index:/usr/share/nginx/html
                        - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
                restart: always

        mysql:
                image: mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: 123123
                        MYSQL_USER: user
                        MYSQL_PASSWORD: 123
                restart: always
